/// EduCinema LMS — Teacher My Salary Page
/// Teachers view their own salary records and payment status.
library;

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import '../../../core/theme/app_theme.dart';
import '../../../core/widgets/shared_widgets.dart';
import '../../../core/network/api_repository.dart';

class TeacherSalaryPage extends StatefulWidget {
  const TeacherSalaryPage({super.key});
  @override
  State<TeacherSalaryPage> createState() => _TeacherSalaryPageState();
}

class _TeacherSalaryPageState extends State<TeacherSalaryPage> {
  final _repo = ApiRepository();
  final _currencyFmt = NumberFormat.currency(locale: 'en_IN', symbol: '₹', decimalDigits: 0);
  bool _loading = true;
  double _totalEarned = 0;
  double _totalPending = 0;
  List<dynamic> _records = [];
  int _selectedYear = DateTime.now().year;

  final List<String> _monthNames = ['','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    setState(() => _loading = true);
    try {
      final data = await _repo.get('/teacher/my-salary', params: {'year': _selectedYear});
      setState(() {
        _totalEarned = (data['total_earned'] ?? 0).toDouble();
        _totalPending = (data['total_pending'] ?? 0).toDouble();
        _records = data['records'] ?? [];
        _loading = false;
      });
    } catch (e) {
      setState(() => _loading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(title: const Text('My Salary')),
      body: _loading
          ? const Center(child: CircularProgressIndicator())
          : RefreshIndicator(
              onRefresh: _load,
              child: ListView(
                padding: const EdgeInsets.all(16),
                children: [
                  _buildSummaryCard(),
                  const SizedBox(height: 20),
                  _buildYearFilter(),
                  const SizedBox(height: 16),
                  SectionHeader(title: 'Salary History (${_records.length})'),
                  const SizedBox(height: 8),
                  if (_records.isEmpty)
                    const EmptyState(icon: Icons.account_balance_wallet_outlined, title: 'No salary records', subtitle: 'Salary records will appear here once generated by admin')
                  else
                    ..._records.map((r) => _buildSalaryCard(r)),
                ],
              ),
            ),
    );
  }

  Widget _buildSummaryCard() {
    return Container(
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        gradient: const LinearGradient(
          colors: [Color(0xFF667EEA), Color(0xFF764BA2)],
          begin: Alignment.topLeft, end: Alignment.bottomRight,
        ),
        borderRadius: BorderRadius.circular(24),
        boxShadow: [BoxShadow(color: const Color(0xFF667EEA).withValues(alpha: 0.35), blurRadius: 20, offset: const Offset(0, 8))],
      ),
      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        Text('Salary Summary', style: GoogleFonts.inter(fontSize: 14, color: Colors.white70)),
        const SizedBox(height: 16),
        Row(children: [
          Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
            Text('Total Earned', style: GoogleFonts.inter(fontSize: 12, color: Colors.white60)),
            const SizedBox(height: 4),
            FittedBox(fit: BoxFit.scaleDown, alignment: Alignment.centerLeft, child: Text(_currencyFmt.format(_totalEarned), style: GoogleFonts.outfit(fontSize: 26, fontWeight: FontWeight.w800, color: Colors.white))),
          ])),
          Container(width: 1, height: 50, color: Colors.white24),
          const SizedBox(width: 16),
          Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
            Text('Pending', style: GoogleFonts.inter(fontSize: 12, color: Colors.white60)),
            const SizedBox(height: 4),
            FittedBox(fit: BoxFit.scaleDown, alignment: Alignment.centerLeft, child: Text(_currencyFmt.format(_totalPending), style: GoogleFonts.outfit(fontSize: 26, fontWeight: FontWeight.w800, color: const Color(0xFFFFD93D)))),
          ])),
        ]),
      ]),
    );
  }

  Widget _buildYearFilter() {
    return Row(children: [
      Text('Year:', style: GoogleFonts.inter(fontSize: 14, fontWeight: FontWeight.w600)),
      const SizedBox(width: 12),
      Container(
        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
        decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(12), border: Border.all(color: Colors.grey.shade200)),
        child: DropdownButtonHideUnderline(
          child: DropdownButton<int>(
            value: _selectedYear, isDense: true,
            style: GoogleFonts.inter(fontSize: 14, color: AppColors.textPrimary, fontWeight: FontWeight.w600),
            items: [2024, 2025, 2026].map((y) => DropdownMenuItem(value: y, child: Text('$y'))).toList(),
            onChanged: (v) { setState(() => _selectedYear = v!); _load(); },
          ),
        ),
      ),
    ]);
  }

  Widget _buildSalaryCard(dynamic r) {
    final status = r['payment_status'] ?? 'Pending';
    final statusColor = status == 'Paid' ? AppColors.success : status == 'Partial' ? AppColors.warning : AppColors.error;
    final month = (r['month'] ?? 1) as int;
    final year = r['year'] ?? 2026;
    final monthName = month >= 1 && month <= 12 ? _monthNames[month] : '$month';

    return Container(
      margin: const EdgeInsets.only(bottom: 10),
      decoration: BoxDecoration(
        color: Colors.white, borderRadius: BorderRadius.circular(16),
        border: Border.all(color: statusColor.withValues(alpha: 0.15)),
        boxShadow: [BoxShadow(color: Colors.black.withValues(alpha: 0.02), blurRadius: 8)],
      ),
      child: ExpansionTile(
        tilePadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
        shape: const Border(),
        leading: Container(
          width: 48, height: 48,
          decoration: BoxDecoration(
            gradient: LinearGradient(colors: status == 'Paid'
                ? [const Color(0xFF43E97B), const Color(0xFF38F9D7)]
                : status == 'Partial'
                    ? [const Color(0xFFFFD93D), const Color(0xFFFFE082)]
                    : [const Color(0xFFFF6B6B), const Color(0xFFFF8E53)]),
            borderRadius: BorderRadius.circular(14),
          ),
          child: Center(child: Text(monthName, style: GoogleFonts.outfit(fontSize: 14, fontWeight: FontWeight.w800, color: Colors.white))),
        ),
        title: Row(children: [
          Expanded(child: Text('$monthName $year', style: GoogleFonts.inter(fontSize: 15, fontWeight: FontWeight.w600), overflow: TextOverflow.ellipsis)),
          const SizedBox(width: 8),
          StatusBadge(label: status, color: statusColor, showDot: true),
        ]),
        subtitle: Text(_currencyFmt.format(r['net_salary'] ?? 0), style: GoogleFonts.outfit(fontSize: 16, fontWeight: FontWeight.w700, color: AppColors.featureBlue)),
        children: [
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 0, 16, 14),
            child: Column(children: [
              const Divider(height: 1),
              const SizedBox(height: 12),
              _row('Basic Salary', _currencyFmt.format(r['basic_salary'] ?? 0)),
              _row('Bonus', _currencyFmt.format(r['bonus'] ?? 0), color: AppColors.success),
              _row('Deductions', '- ${_currencyFmt.format(r['deductions'] ?? 0)}', color: AppColors.error),
              const Divider(height: 16),
              _row('Net Salary', _currencyFmt.format(r['net_salary'] ?? 0), bold: true),
              if (status == 'Partial') ...[
                _row('Paid Amount', _currencyFmt.format(r['paid_amount'] ?? 0), color: AppColors.success),
                _row('Pending Amount', _currencyFmt.format((r['net_salary'] ?? 0) - (r['paid_amount'] ?? 0)), color: AppColors.error),
              ],
              if (r['payment_date'] != null) _row('Payment Date', r['payment_date']),
              if (r['payment_method'] != null) _row('Method', r['payment_method']),
              if (r['transaction_id'] != null) _row('Transaction ID', r['transaction_id']),
              if (r['notes'] != null) _row('Notes', r['notes']),
            ]),
          ),
        ],
      ),
    );
  }

  Widget _row(String label, String value, {Color? color, bool bold = false}) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 3),
      child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [
        Text(label, style: GoogleFonts.inter(fontSize: 13, color: AppColors.textSecondary)),
        Flexible(child: Text(value, style: GoogleFonts.inter(fontSize: 13, fontWeight: bold ? FontWeight.w700 : FontWeight.w600, color: color ?? AppColors.textPrimary), textAlign: TextAlign.end)),
      ]),
    );
  }
}
