/// EduCinema LMS — Student Fee Status Page
/// Students view their fee payment status and history.
library;

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import '../../../core/theme/app_theme.dart';
import '../../../core/widgets/shared_widgets.dart';
import '../../../core/network/api_repository.dart';

class StudentFeeStatusPage extends StatefulWidget {
  const StudentFeeStatusPage({super.key});
  @override
  State<StudentFeeStatusPage> createState() => _StudentFeeStatusPageState();
}

class _StudentFeeStatusPageState extends State<StudentFeeStatusPage> {
  final _repo = ApiRepository();
  final _currencyFmt = NumberFormat.currency(locale: 'en_IN', symbol: '₹', decimalDigits: 0);
  bool _loading = true;
  double _totalFee = 0;
  double _totalPaid = 0;
  double _totalPending = 0;
  double _totalFine = 0;
  List<dynamic> _records = [];

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    setState(() => _loading = true);
    try {
      final data = await _repo.get('/student/my-fees');
      setState(() {
        _totalFee = (data['total_fee'] ?? 0).toDouble();
        _totalPaid = (data['total_paid'] ?? 0).toDouble();
        _totalPending = (data['total_pending'] ?? 0).toDouble();
        _totalFine = (data['total_fine'] ?? 0).toDouble();
        _records = data['records'] ?? [];
        _loading = false;
      });
    } catch (e) {
      setState(() => _loading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(title: const Text('My Fees')),
      body: _loading
          ? const Center(child: CircularProgressIndicator())
          : RefreshIndicator(
              onRefresh: _load,
              child: ListView(
                padding: const EdgeInsets.all(16),
                children: [
                  _buildSummaryCard(),
                  const SizedBox(height: 16),
                  _buildProgressCard(),
                  const SizedBox(height: 20),
                  SectionHeader(title: 'Fee Records (${_records.length})'),
                  const SizedBox(height: 8),
                  if (_records.isEmpty)
                    const EmptyState(icon: Icons.receipt_long_outlined, title: 'No fee records', subtitle: 'Fee records will appear here once generated by admin')
                  else
                    ..._records.map((r) => _buildFeeCard(r)),
                ],
              ),
            ),
    );
  }

  Widget _buildSummaryCard() {
    return Container(
      padding: const EdgeInsets.all(24),
      decoration: BoxDecoration(
        gradient: const LinearGradient(
          colors: [Color(0xFF667EEA), Color(0xFF764BA2)],
          begin: Alignment.topLeft, end: Alignment.bottomRight,
        ),
        borderRadius: BorderRadius.circular(24),
        boxShadow: [BoxShadow(color: const Color(0xFF667EEA).withValues(alpha: 0.35), blurRadius: 20, offset: const Offset(0, 8))],
      ),
      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        Text('Fee Overview', style: GoogleFonts.inter(fontSize: 14, color: Colors.white70)),
        const SizedBox(height: 16),
        Row(children: [
          Expanded(child: _summaryItem('Total Fee', _currencyFmt.format(_totalFee), Colors.white)),
          Expanded(child: _summaryItem('Paid', _currencyFmt.format(_totalPaid), const Color(0xFF43E97B))),
        ]),
        const SizedBox(height: 16),
        Row(children: [
          Expanded(child: _summaryItem('Pending', _currencyFmt.format(_totalPending), const Color(0xFFFFD93D))),
          Expanded(child: _summaryItem('Fine', _currencyFmt.format(_totalFine), const Color(0xFFFF6B6B))),
        ]),
      ]),
    );
  }

  Widget _summaryItem(String label, String value, Color color) {
    return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      Text(label, style: GoogleFonts.inter(fontSize: 11, color: Colors.white60)),
      const SizedBox(height: 4),
      FittedBox(fit: BoxFit.scaleDown, alignment: Alignment.centerLeft, child: Text(value, style: GoogleFonts.outfit(fontSize: 18, fontWeight: FontWeight.w800, color: color))),
    ]);
  }

  Widget _buildProgressCard() {
    final progress = _totalFee > 0 ? (_totalPaid / _totalFee).clamp(0.0, 1.0) : 0.0;
    final pct = (progress * 100).round();
    final color = pct >= 100 ? AppColors.success : pct >= 50 ? AppColors.warning : AppColors.error;

    return GlassCard(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [
        Text('Payment Progress', style: GoogleFonts.inter(fontSize: 14, fontWeight: FontWeight.w600)),
        Text('$pct%', style: GoogleFonts.outfit(fontSize: 20, fontWeight: FontWeight.w800, color: color)),
      ]),
      const SizedBox(height: 12),
      ClipRRect(
        borderRadius: BorderRadius.circular(6),
        child: LinearProgressIndicator(
          value: progress,
          minHeight: 10,
          backgroundColor: Colors.grey.shade100,
          valueColor: AlwaysStoppedAnimation(color),
        ),
      ),
      const SizedBox(height: 8),
      Text(
        pct >= 100 ? '✓ All fees paid!' : '₹${_totalPending.toStringAsFixed(0)} remaining',
        style: GoogleFonts.inter(fontSize: 12, color: color, fontWeight: FontWeight.w600),
      ),
    ]));
  }

  Widget _buildFeeCard(dynamic r) {
    final status = r['status'] ?? 'Pending';
    final statusColor = status == 'Paid' ? AppColors.success : status == 'Partial' ? AppColors.warning : AppColors.error;
    final totalFee = ((r['total_fee'] ?? 0) as num).toDouble();
    final paidAmt = ((r['paid_amount'] ?? 0) as num).toDouble();
    final pendingAmt = ((r['pending_amount'] ?? 0) as num).toDouble();
    final fineAmt = ((r['fine_amount'] ?? 0) as num).toDouble();
    final month = r['month'] ?? '';
    final year = r['year'] ?? '';
    final dueDate = r['due_date'];
    final progress = totalFee > 0 ? (paidAmt / (totalFee + fineAmt)).clamp(0.0, 1.0) : 0.0;

    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      decoration: BoxDecoration(
        color: Colors.white, borderRadius: BorderRadius.circular(16),
        border: Border.all(color: statusColor.withValues(alpha: 0.15)),
        boxShadow: [BoxShadow(color: Colors.black.withValues(alpha: 0.02), blurRadius: 8)],
      ),
      child: ExpansionTile(
        tilePadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
        shape: const Border(),
        leading: Container(
          width: 48, height: 48,
          decoration: BoxDecoration(
            gradient: LinearGradient(colors: status == 'Paid'
                ? [const Color(0xFF43E97B), const Color(0xFF38F9D7)]
                : status == 'Partial'
                    ? [const Color(0xFFFFD93D), const Color(0xFFFF8E53)]
                    : [const Color(0xFFFF6B6B), const Color(0xFFFF8E53)]),
            borderRadius: BorderRadius.circular(14),
          ),
          child: Center(child: Icon(
            status == 'Paid' ? Icons.check_circle_rounded : Icons.hourglass_top_rounded,
            color: Colors.white, size: 22,
          )),
        ),
        title: Row(children: [
          Expanded(child: Text(month.isNotEmpty ? '$month $year' : 'Fee #${r['id']}', style: GoogleFonts.inter(fontSize: 15, fontWeight: FontWeight.w600), overflow: TextOverflow.ellipsis)),
          const SizedBox(width: 8),
          StatusBadge(label: status, color: statusColor, showDot: true),
        ]),
        subtitle: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
          const SizedBox(height: 6),
          ClipRRect(
            borderRadius: BorderRadius.circular(4),
            child: LinearProgressIndicator(
              value: progress, minHeight: 6,
              backgroundColor: Colors.grey.shade100,
              valueColor: AlwaysStoppedAnimation(statusColor),
            ),
          ),
        ]),
        children: [
          Padding(
            padding: const EdgeInsets.fromLTRB(16, 0, 16, 14),
            child: Column(children: [
              const Divider(height: 1),
              const SizedBox(height: 12),
              _row('Total Fee', _currencyFmt.format(totalFee)),
              _row('Paid Amount', _currencyFmt.format(paidAmt), color: AppColors.success),
              if (fineAmt > 0) _row('Fine', _currencyFmt.format(fineAmt), color: AppColors.error),
              _row('Pending', _currencyFmt.format(pendingAmt), color: pendingAmt > 0 ? AppColors.error : AppColors.success, bold: true),
              if (dueDate != null) _row('Due Date', dueDate),
              if (r['payment_date'] != null) _row('Paid On', r['payment_date']),
              if (r['payment_method'] != null) _row('Method', r['payment_method']),
              if (r['installment'] != null) _row('Installment', r['installment']),
              if (r['notes'] != null) _row('Notes', r['notes']),
            ]),
          ),
        ],
      ),
    );
  }

  Widget _row(String label, String value, {Color? color, bool bold = false}) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 3),
      child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [
        Text(label, style: GoogleFonts.inter(fontSize: 13, color: AppColors.textSecondary)),
        Flexible(child: Text(value, style: GoogleFonts.inter(fontSize: 13, fontWeight: bold ? FontWeight.w700 : FontWeight.w600, color: color ?? AppColors.textPrimary), textAlign: TextAlign.end)),
      ]),
    );
  }
}
